# Generated by Django 3.0.3 on 2020-05-20 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200520_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='message',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='service',
        ),
    ]
