# Generated by Django 3.0.3 on 2020-05-20 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200520_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='budget',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='deadline',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='message',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='service',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
