# Generated by Django 3.0.3 on 2020-05-20 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200520_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('message', models.CharField(max_length=2000, null=True)),
                ('deadline', models.CharField(max_length=500, null=True)),
                ('service', models.CharField(max_length=200, null=True)),
                ('budget', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
